ela_feature_names=['disp.ratio_mean_02', 'disp.ratio_mean_05', 'disp.ratio_mean_10',
       'disp.ratio_mean_25', 'disp.ratio_median_02', 'disp.ratio_median_05',
       'disp.ratio_median_10', 'disp.ratio_median_25', 'disp.diff_mean_02',
       'disp.diff_mean_05', 'disp.diff_mean_10', 'disp.diff_mean_25',
       'disp.diff_median_02', 'disp.diff_median_05', 'disp.diff_median_10',
       'disp.diff_median_25', 'ela_meta.lin_simple.adj_r2',
       'ela_meta.lin_simple.intercept', 'ela_meta.lin_simple.coef.min',
       'ela_meta.lin_simple.coef.max', 'ela_meta.lin_simple.coef.max_by_min',
       'ela_meta.lin_w_interact.adj_r2', 'ela_meta.quad_simple.adj_r2',
       'ela_meta.quad_simple.cond', 'ela_meta.quad_w_interact.adj_r2',
       'ela_level.mmce_lda_10', 'ela_level.mmce_qda_10',
       'ela_level.mmce_mda_10', 'ela_level.lda_qda_10', 'ela_level.lda_mda_10',
       'ela_level.qda_mda_10', 'ela_level.mmce_lda_25',
       'ela_level.mmce_qda_25', 'ela_level.mmce_mda_25',
       'ela_level.lda_qda_25', 'ela_level.lda_mda_25', 'ela_level.qda_mda_25',
       'ela_level.mmce_lda_50', 'ela_level.mmce_qda_50',
       'ela_level.mmce_mda_50', 'ela_level.lda_qda_50', 'ela_level.lda_mda_50',
       'ela_level.qda_mda_50', 'ela_distr.skewness', 'ela_distr.kurtosis',
       'ela_distr.number_of_peaks', 'ic.h.max', 'ic.eps.max',
       'ic.eps.ratio', 'ic.m0', 'nbc.nn_nb.sd_ratio', 'nbc.nn_nb.mean_ratio',
       'nbc.nn_nb.cor', 'nbc.dist_ratio.coeff_var', 'nbc.nb_fitness.cor',
       'pca.expl_var.cov_x', 'pca.expl_var.cor_x', 'pca.expl_var.cov_init',
       'pca.expl_var.cor_init', 'pca.expl_var_PC1.cov_x',
       'pca.expl_var_PC1.cor_x', 'pca.expl_var_PC1.cov_init',
       'pca.expl_var_PC1.cor_init']

removed=['ic.eps.s']